title: "GitHub Emoji Cheat Sheet: categorized and searchable"
description: 
  Always up to date list of all supported GitHub emojis.<br/>
  Includes emoji names, images, markdown codes and Unicode characters.<br/>
  Emojis are all categorized and searchable, with convienent click-to-copy emoji to clipboard.
baseurl: "/github-emoji-cheatsheet"
url: "https://phw198.github.io"

show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - docs/
  - ruby/
  - script/
  - vendor/