#!/bin/sh

set -e

bundle exec jekyll build

mkdir -p ./tmp/github-emoji-cheatsheet
cp -r ./_site/* ./tmp/github-emoji-cheatsheet/
bundle exec htmlproofer ./tmp --check-html --check-sri --disable-external --url-ignore "/googletagmanager.com/","/googlesyndication.com/"
rm -rf ./tmp

bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-hacker.gemspec
